<?php
protegerme();
$GLOBAL_MOSTRAR_PIE = false;
set_time_limit(0);
/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, check official documentation. It is available
 * online and also for download on phpMyEdit project management page:
 *
 * http://platon.sk/projects/main_page.php?project_id=5
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.1
 *       phpMyEdit.class.php core class: 1.204
 *            phpMyEditSetup.php script: 1.50
 *              generating setup script: 1.50
 */

// MySQL host name, user name, password, database, and table
$opts['dbh'] = $db_link;
$REFERENCIA = (isset($_POST['con_referencia'])) ? '?referencia=categorias' : '';
$opts['page_name'] = PROY_URL_ACTUAL.$REFERENCIA;
$opts['tb'] = db_prefijo.'categorias';

// Name of field which is the unique key
$opts['key'] = 'codigo_categoria';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'int';

// Sorting field(s)
$opts['sort_field'] = array('codigo_categoria');

// Number of records to display on the screen
// Value of -1 lists all records in a table
$opts['inc'] = 15;

// Options you wish to give the users
// A - add,  C - change, P - copy, V - view, D - delete,
// F - filter, I - initial sort suppressed
$opts['options'] = 'ACPVDF';

// Number of lines to display on multiple selection filters
$opts['multiple'] = '4';

// Navigation style: B - buttons (default), T - text links, G - graphic links
// Buttons position: U - up, D - down (default)
$opts['navigation'] = 'DB';

// Display special page elements
$opts['display'] = array(
	'form'  => true,
	'query' => true,
	'sort'  => true,
	'time'  => false,
	'tabs'  => true
);

// Set default prefixes for variables
$opts['js']['prefix']               = 'PME_js_';
$opts['dhtml']['prefix']            = 'PME_dhtml_';
$opts['cgi']['prefix']['operation'] = 'PME_op_';
$opts['cgi']['prefix']['sys']       = 'PME_sys_';
$opts['cgi']['prefix']['data']      = 'PME_data_';

/* Get the user's default language and use it if possible or you can
   specify particular one you want to use. Refer to official documentation
   for list of available languages. */
$opts['language'] = 'ES-AR-UTF8';

$opts['fdd']['codigo_categoria'] = array(
  'name'     => 'Codigo categoria',
  'select'   => 'T',
  //'options'  => 'AVCPDR', // auto increment
  'maxlen'   => 11,
  'default'  => '0',
  'sort'     => true
);
$opts['fdd']['titulo'] = array(
  'name'     => 'Titulo',
  'select'   => 'T',
  'maxlen'   => 100,
  'sort'     => true
);
$opts['fdd']['descripcion'] = array(
  'name'     => 'Descripcion',
  'select'   => 'T',
  'maxlen'   => -1,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'sort'     => true
);
$opts['fdd']['codigo_menu'] = array(
  'name'     => 'Código menú',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['codigo_menu']['values']['table']       = db_prefijo.'menu';
$opts['fdd']['codigo_menu']['values']['column']      = 'codigo_menu';
$opts['fdd']['codigo_menu']['values']['description'] = 'titulo'; // optional

$opts['fdd']['mostrar_en_vitrina'] = array(
  'name'     => 'Mostrar en vitrina?',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['tipo'] = array(
  'name'     => 'Tipo de categoría',
  'select'   => 'T',
  'maxlen'   => -1,
  'sort'     => true,
  'values'   => array(
                "ocasion",
                "tipo",
                "especial")
);

// Now important call to phpMyEdit
new phpMyEdit($opts);

?>
