<?php
protegerme();
/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, check official documentation. It is available
 * online and also for download on phpMyEdit project management page:
 *
 * http://platon.sk/projects/main_page.php?project_id=5
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.1
 *       phpMyEdit.class.php core class: 1.204
 *            phpMyEditSetup.php script: 1.50
 *              generating setup script: 1.50
 */

// MySQL host name, user name, password, database, and table
$opts['dbh'] = $db_link;
$opts['page_name'] = PROY_URL_ACTUAL;
$opts['tb'] = db_prefijo.'SSL_compra_contenedor';

// Name of field which is the unique key
$opts['key'] = 'codigo_compra';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'int';

// Sorting field(s)
$opts['sort_field'] = array('codigo_compra');

// Number of records to display on the screen
// Value of -1 lists all records in a table
$opts['inc'] = 15;

// Options you wish to give the users
// A - add,  C - change, P - copy, V - view, D - delete,
// F - filter, I - initial sort suppressed
$opts['options'] = 'ACPVDF';

// Number of lines to display on multiple selection filters
$opts['multiple'] = '4';

// Navigation style: B - buttons (default), T - text links, G - graphic links
// Buttons position: U - up, D - down (default)
$opts['navigation'] = 'DB';

// Display special page elements
$opts['display'] = array(
	'form'  => true,
	'query' => true,
	'sort'  => true,
	'time'  => false,
	'tabs'  => true
);

// Set default prefixes for variables
$opts['js']['prefix']               = 'PME_js_';
$opts['dhtml']['prefix']            = 'PME_dhtml_';
$opts['cgi']['prefix']['operation'] = 'PME_op_';
$opts['cgi']['prefix']['sys']       = 'PME_sys_';
$opts['cgi']['prefix']['data']      = 'PME_data_';

$opts['language'] = 'ES-AR-UTF8';

$opts['fdd']['codigo_compra'] = array(
  'name'     => 'Codigo compra',
  'select'   => 'T',
  'options'  => 'AVCPDR', // auto increment
  'maxlen'   => 11,
  'default'  => '0',
  'sort'     => true
);
$opts['fdd']['codigo_usuario'] = array(
  'name'     => 'Codigo usuario',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['codigo_variedad'] = array(
  'name'     => 'Codigo variedad',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['precio_grabado'] = array(
  'name'     => 'Precio grabado',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['n_credito'] = array(
  'name'     => 'N credito',
  'select'   => 'T',
  'maxlen'   => -1,
  'sort'     => true
);

$opts['fdd']['n_credito']['sql'] = 'AES_DECRYPT(n_credito,"'.db__key_str.'")';
$opts['fdd']['n_credito']['sqlw'] = 'AES_ENCRYPT($val_qas,"'.db__key_str.'")';

$opts['fdd']['tipo_t_credito'] = array(
  'name'     => 'Tipo t credito',
  'select'   => 'T',
  'maxlen'   => 150,
  'sort'     => true
);
$opts['fdd']['fecha_exp_t_credito'] = array(
  'name'     => 'Fecha exp t credito',
  'select'   => 'T',
  'maxlen'   => 15,
  'sort'     => true
);
$opts['fdd']['pin_4_reverso_t_credito'] = array(
  'name'     => 'Pin 4 reverso t credito',
  'select'   => 'T',
  'maxlen'   => 12,
  'sort'     => true
);
$opts['fdd']['direccion_entrega'] = array(
  'name'     => 'Direccion entrega',
  'select'   => 'T',
  'maxlen'   => -1,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'sort'     => true
);
$opts['fdd']['fecha_entrega'] = array(
  'name'     => 'Fecha entrega',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['tarjeta_de'] = array(
  'name'     => 'Tarjeta de',
  'select'   => 'T',
  'maxlen'   => 150,
  'sort'     => true
);
$opts['fdd']['tarjeta_para'] = array(
  'name'     => 'Tarjeta para',
  'select'   => 'T',
  'maxlen'   => 150,
  'sort'     => true
);
$opts['fdd']['tarjeta_cuerpo'] = array(
  'name'     => 'Tarjeta cuerpo',
  'select'   => 'T',
  'maxlen'   => -1,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'sort'     => true
);
$opts['fdd']['estado'] = array(
  'name'     => 'Estado',
  'select'   => 'T',
  'maxlen'   => 45,
  'values'   => array(
                  "nuevo",
                  "aprobado",
                  "cobrado",
                  "transito",
                  "enviado",
                  "error_pago",
                  "error_direccion",
                  "error_flor360"),
  'sort'     => true
);
$opts['fdd']['estado_notas'] = array(
  'name'     => 'Estado notas',
  'select'   => 'T',
  'maxlen'   => 196605,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'sort'     => true
);
$opts['fdd']['usuario_notas'] = array(
  'name'     => 'Usuario notas',
  'select'   => 'T',
  'maxlen'   => -1,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'sort'     => true
);

if (isset($_GET['modificar']) && is_numeric($_GET['modificar']))
{
    $_POST['con_referencia']=true;
    $_POST['PME_sys_sfn[0]']='0';
    $_POST['PME_sys_fl']='0';
    $_POST['PME_sys_qfn']='';
    $_POST['PME_sys_fm']='0';
    $_POST['PME_sys_rec']=$_GET['modificar'];
    $_POST['PME_sys_operation']='Cambiar';
}

// Now important call to phpMyEdit
new phpMyEdit($opts);

?>
